const express = require('express');
const cors = require('cors');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const userRouter = require('./routes/userRoutes');
const taskRouter = require('./routes/taskRoutes');

const projectRouter = require('./routes/projectRoutes');
const projectPhaseRouter = require('./routes/projectPhaseRoutes');
const resourceRouter = require('./routes/resourceRoutes');
const resourceGroupRouter = require('./routes/resourceGroupRoutes');
const teamRouter = require('./routes/teamRoutes');
const chatRouter = require('./routes/chatRoutes');
const messageRouter = require('./routes/messageRoutes');

const app = express();
app.use(express.json({ limit: '10kb' }));
app.use(express.urlencoded({ extended: true, limit: '10kb' }));
app.use(cookieParser());
app.use(cors('*'));
app.use(compression());
app.use('/api/v1/users', userRouter);
app.use('/api/v1/tasks', taskRouter);
app.use('/api/v1/projects', projectRouter);
app.use('/api/v1/project-phases', projectPhaseRouter);
app.use('/api/v1/resources', resourceRouter);
app.use('/api/v1/resource-groups', resourceGroupRouter);
app.use('/api/v1/teams', teamRouter);
app.use('/api/v1/chats', chatRouter);
app.use('/api/v1/messages', messageRouter);
module.exports = app;
